### ISSUE TITLE
decoder set_property if None

### ISSUE THREAD

**Issue by will-moore** [openmicroscopy/omero-marshal#18]
I think that the Decoder ```set_property()``` should not do anything if the value is ```None```, in the same way that the encoders do ```set_if_not_none()```.
Otherwise, you end up with empty strings instead of None. E.g.
If I encode and then decode a Project, the description is changed from None to empty rstring:
```
>>> p = ProjectI()
>>> p.name = rstring('test')
>>> encoder = get_encoder(p.__class__)
>>> pdict = encoder.encode(p)
>>> 'Description' in pdict
False
>>> decoder = get_decoder(pdict['@type'])
>>> project = decoder.decode(pdict)
>>> project.description
object #0 (::omero::RString)
{
    _val = 
}
>>> p.description
>>> p.description is None
True
>>> project.description is None
False
```

**Comment by sbesson** [comment]
Having `Decoder.set_property()` return early if the value is `None` sounds like the right thing to do a priori. The largest effort required here might be the extension of the unit tests coverage to check all objects with and without a description.
