### ISSUE TITLE
https://github.com/openmicroscopy/omero-marshal/blob/master/omero_marshal/decode/decoders/shape.py#L27

### ISSUE THREAD

**Issue by waxenegger** [openmicroscopy/omero-marshal#5]
It could be I'm missing information on how to avoid this but using omero_marshal I noticed that if don't provide FontSize/StrokeWidth in my json the to_unit code (https://github.com/openmicroscopy/omero-marshal/blob/00f3e1f2198f60b7e665da098699a53c5c6a5d6f/omero_marshal/decode/__init__.py#L28) will give me grief.

I can work around this by providing the information but it means that I have to send more bytes for optional info. In particular, any shape that is not a label will need a FontSize even if it doesn't have text on it. It might make sense to marshal the font properties only conditionally on presence of text.

I suppose one could make a default value of unit 1 (px/pt) for strokeWidth as well so a client doesn't need to have to submit the info but the argument is not a strong as in the above case with text and font

**Comment by chris-allan** [comment]
I would just add the following to `to_unit()`:

```
if v is None:
    return None
```

Add accompanying test cases and we should be good to go.

**Comment by waxenegger** [comment]
suggested change and unit test modifications: https://github.com/openmicroscopy/omero-marshal/pull/6
